version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  # prometheus:
  #   image: prom/pushgateway
  #   ports:
  #     - "9091:9091"
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   networks:
  #     - monitoring
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    # expose:
    #   - "8081"
    ports:
      - "8081:8081"
    command: "node app.js"

  node2:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    # expose:
    #   - "8081"
    ports:
      - "8082:8082"
    command: "node app2.js "

  postgres:
    image: postgres:16
    ports:
      - 8083:5432
    environment:
      POSTGRES_PASSWORD: example
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data      
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: boholch@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dUcgOEi3k13L3GE1Fg0RIHkHK1jjr506lAZa4vFt8CPuUbGgxBvHPDbEdSSCM9Mk
    ports:
      - 8084:80
  postgres-exporter:
    # image: quay.io/prometheuscommunity/postgres-exporter
    image: prometheuscommunity/postgres-exporter
    ports:
      - 8085:9187
    environment:
      # DATA_SOURCE_NAME: postgresql://postgres:example@192.168.62.101:8083/postgres?sslmode=disable
      DATA_SOURCE_NAME: postgresql://postgres:example@192.168.62.101:8083
    restart: always
    depends_on:
      - postgres

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
    driver: local